<?php
// +--------------------------------------------------------------------------+
// | Media Gallery Plugin - Geeklog                                           |
// +--------------------------------------------------------------------------+
// | Set configuration options for Media Gallery Plugin.                      |
// +--------------------------------------------------------------------------+
// | Copyright (C) 2015 by the following authors:                             |
// |                                                                          |
// | Yoshinori Tahara       taharaxp AT gmail DOT com                         |
// |                                                                          |
// | Based on the Media Gallery Plugin for glFusion CMS                       |
// | Copyright (C) 2005-2010 by the following authors:                        |
// |                                                                          |
// | Mark R. Evans          mark AT glfusion DOT org                          |
// +--------------------------------------------------------------------------+
// |                                                                          |
// | This program is free software; you can redistribute it and/or            |
// | modify it under the terms of the GNU General Public License              |
// | as published by the Free Software Foundation; either version 2           |
// | of the License, or (at your option) any later version.                   |
// |                                                                          |
// | This program is distributed in the hope that it will be useful,          |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of           |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            |
// | GNU General Public License for more details.                             |
// |                                                                          |
// | You should have received a copy of the GNU General Public License        |
// | along with this program; if not, write to the Free Software Foundation,  |
// | Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.          |
// |                                                                          |
// +--------------------------------------------------------------------------+
//

require_once '../../../lib-common.php';
require_once '../../auth.inc.php';

$sub  = isset($_GET['s'])    ? COM_applyFilter($_GET['s'])         : '';
$msg  = isset($_GET['msg'])  ? COM_applyFilter($_GET['msg'], true) : 0;
$mode = isset($_GET['mode']) ? COM_applyFilter($_GET['mode'])      : '';

// Configuration and moderation deliberately use separate Geeklog features.
// Keep the configuration area restricted to mediagallery.config, while
// allowing mediagallery.admin to use only the submission edit/save routes
// generated by Geeklog's moderation screen.
$isModerationRoute = ($mode === 'editsubmission' || $mode === 'savemedia');
$hasAccess = SEC_hasRights('mediagallery.config')
    || ($isModerationRoute && SEC_hasRights('mediagallery.admin'));

if (!$hasAccess) {
    COM_errorLog("Someone has tried to illegally access the Media Gallery administration page. "
               . "User id: {$_USER['uid']}, Username: {$_USER['username']}, IP: " . $_SERVER['REMOTE_ADDR'], 1);
    $display = COM_startBlock($LANG_MG00['access_denied']);
    $display .= $LANG_MG00['access_denied_msg'];
    $display .= COM_endBlock();
    $display = COM_createHTMLDocument($display);
    COM_output($display);
    exit;
}

require_once $_MG_CONF['path_admin'] . 'navigation.php';

// main menu for media gallery administration

$sub_menu = '';
switch ($sub) {
    case 'm': $sub_menu = 'member_albums';  break;
    case 'b': $sub_menu = 'batch_sessions'; break;
    case 'c': $sub_menu = 'miscellaneous';  break;
}

$home_url = $_CONF['site_url'] . '/admin/moderation.php';

if ($mode == 'editsubmission') {
    $media_id = isset($_GET['id']) ? COM_applyFilter($_GET['id']) : '';
    if (empty($media_id)) {
        COM_redirect($home_url);
    }

    $escapedMediaId = DB_escapeString($media_id);
    $album_id = (int) DB_getItem(
        $_TABLES['mg_media_album_queue'],
        'album_id',
        "media_id='" . $escapedMediaId . "'"
    );
    if ($album_id <= 0 || DB_count($_TABLES['mg_mediaqueue'], 'media_id', $media_id) !== 1) {
        COM_errorLog('MediaGallery: invalid queued media requested for moderation edit: ' . $media_id, 1);
        COM_redirect($home_url);
    }

    require_once $_CONF['path'] . 'plugins/mediagallery/include/mediamanage.php';
    $actionURL = $_CONF['site_url'] . '/admin/plugins/mediagallery/index.php?mode=savemedia';
    $display = MG_mediaEdit($album_id, $media_id, $actionURL, 1);
    $display = COM_createHTMLDocument($display);
    COM_output($display);
    exit;
} else if ($mode == 'savemedia') {
    $post_mode = isset($_POST['mode']) ? COM_applyFilter($_POST['mode']) : '';
    if (!empty($LANG_MG01['save']) && $post_mode == $LANG_MG01['save']) {
        $album_id = isset($_POST['album_id']) ? COM_applyFilter($_POST['album_id'], true) : 0;
        $media_id = isset($_POST['mid']) ? COM_applyFilter($_POST['mid']) : '';
        $queue = isset($_POST['queue']) ? COM_applyFilter($_POST['queue'], true) : 0;

        if (!empty($media_id) && !empty($album_id) && $queue == 1) {
            // Bind the posted queue item back to the album selected by the
            // moderation list before handing the mutation to mediamanage.php.
            if (DB_count(
                $_TABLES['mg_media_album_queue'],
                array('album_id', 'media_id'),
                array((int) $album_id, $media_id)
            ) !== 1) {
                COM_errorLog('MediaGallery: rejected moderation edit because queued media is not bound to the posted album.', 1);
                COM_redirect($home_url);
            }

            require_once $_CONF['path'] . 'plugins/mediagallery/include/mediamanage.php';
            MG_saveMediaEdit($album_id, $media_id, $home_url);
        }
    }
    COM_redirect($home_url);
}

$display = COM_startBlock($LANG_MG00['admin'], '', COM_getBlockTemplate('_admin_block', 'header'));
$display .= MG_showAdminMenu($sub_menu);
if ($msg > 0) {
    $display .= COM_showMessageText($LANG_MG09[$msg]);
}
$display .= COM_endBlock(COM_getBlockTemplate('_admin_block', 'footer'));
if (empty($sub_menu)) {
    $display .= plugin_showstats_mediagallery(0);
}
$display = COM_createHTMLDocument($display);

COM_output($display);
?>